study(title="Directional Movement Index", shorttitle="DMI")
len = input(14, minval=1, title="DI Length")
lensig = input(14, title="ADX Smoothing", minval=1, maxval=50)

up = change(high)
down = -change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = rma(tr, len)
plus = fixnan(100 * rma(plusDM, len) / trur)
minus = fixnan(100 * rma(minusDM, len) / trur)
sum = plus + minus
adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)

color = plus > plus[1] ? gray : minus > minus[1] ? red : black
color2 = adx > adx[1] ? green : red

p1 = plot(plus, color=orange, title="+DI", linewidth=3,transp=0)
p2 = plot(minus, color=blue, title="-DI", linewidth=4,transp=0)
fill(p1,p2, color=color, transp=85, title="Fill")
hline(40, title="Signal line", linestyle=line, linewidth=1, color=white)
hline(20, title="Signal line", linestyle=line, linewidth=1, color=white)
plot(adx, color=color2, title="ADX", linewidth=3,transp=0)